/********************************************************************************
** Form generated from reading UI file 'dashboard.ui'
**
** Created by: Qt User Interface Compiler version 6.4.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DASHBOARD_H
#define UI_DASHBOARD_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Dashboard
{
public:
    QWidget *centralwidget;
    QHBoxLayout *horizontalLayout;
    QWidget *widget;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QLabel *label_5;
    QLabel *label_7;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QLabel *label_2;
    QLabel *label_8;
    QWidget *page_2;
    QLabel *label_3;
    QWidget *page_5;
    QLabel *label_176;
    QStackedWidget *stackedWidget_5;
    QWidget *page_18;
    QPushButton *pushButton_23;
    QLabel *label_177;
    QLabel *label_178;
    QLabel *label_179;
    QLabel *label_180;
    QLabel *label_181;
    QWidget *page_19;
    QPushButton *pushButton_24;
    QLabel *label_182;
    QLabel *label_183;
    QLabel *label_184;
    QLabel *label_185;
    QLabel *label_186;
    QLabel *label_187;
    QLabel *label_188;
    QLabel *label_189;
    QLabel *label_190;
    QWidget *page_4;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_20;
    QLabel *label_21;
    QTextEdit *textEdit_2;
    QLabel *label_22;
    QPushButton *pushButton_8;
    QPushButton *pushButton_10;
    QLineEdit *lineEdit;
    QComboBox *comboBox;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QLabel *label_24;
    QStackedWidget *stackedWidget_2;
    QWidget *page_6;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_145;
    QLabel *label_144;
    QLabel *label_140;
    QLabel *label_143;
    QLabel *label_147;
    QLabel *label_146;
    QLabel *label_23;
    QLabel *label_149;
    QLabel *label_154;
    QLabel *label_152;
    QLabel *label_148;
    QLabel *label_153;
    QLabel *label_150;
    QLabel *label_151;
    QLabel *label_158;
    QLabel *label_160;
    QLabel *label_157;
    QLabel *label_161;
    QLabel *label_156;
    QLabel *label_155;
    QLabel *label_159;
    QLabel *label_164;
    QLabel *label_168;
    QLabel *label_166;
    QLabel *label_165;
    QLabel *label_167;
    QLabel *label_162;
    QLabel *label_163;
    QLabel *label_170;
    QLabel *label_173;
    QLabel *label_174;
    QLabel *label_172;
    QLabel *label_171;
    QLabel *label_169;
    QLabel *label_175;
    QWidget *page_7;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QWidget *page_8;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QWidget *page_9;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QWidget *page_10;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *label_73;
    QLabel *label_74;
    QStackedWidget *stackedWidget_3;
    QWidget *page_11;
    QLabel *label_75;
    QLabel *label_76;
    QLabel *label_77;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLabel *label_83;
    QLabel *label_84;
    QWidget *page_12;
    QLabel *label_85;
    QLabel *label_86;
    QLabel *label_87;
    QLabel *label_88;
    QLabel *label_89;
    QLabel *label_90;
    QLabel *label_91;
    QLabel *label_92;
    QLabel *label_93;
    QLabel *label_94;
    QWidget *page_13;
    QLabel *label_95;
    QLabel *label_96;
    QLabel *label_97;
    QLabel *label_98;
    QLabel *label_99;
    QLabel *label_100;
    QLabel *label_101;
    QLabel *label_102;
    QLabel *label_103;
    QLabel *label_104;
    QWidget *page_14;
    QLabel *label_105;
    QLabel *label_106;
    QLabel *label_107;
    QLabel *label_108;
    QLabel *label_109;
    QLabel *label_110;
    QLabel *label_111;
    QLabel *label_112;
    QLabel *label_113;
    QLabel *label_114;
    QWidget *page_15;
    QLabel *label_115;
    QLabel *label_116;
    QLabel *label_117;
    QLabel *label_118;
    QLabel *label_119;
    QLabel *label_120;
    QLabel *label_121;
    QLabel *label_122;
    QLabel *label_123;
    QLabel *label_124;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QLabel *label_128;
    QLabel *label_129;
    QLabel *label_130;
    QLabel *label_131;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QLineEdit *lineEdit_8;
    QLineEdit *lineEdit_9;
    QWidget *page_3;
    QLabel *label_4;
    QStackedWidget *stackedWidget_4;
    QWidget *page_16;
    QLabel *label_125;
    QLineEdit *lineEdit_5;
    QPushButton *pushButton_19;
    QLabel *label_126;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_7;
    QLabel *label_127;
    QLabel *label_132;
    QWidget *page_17;
    QComboBox *comboBox_2;
    QLabel *label_133;
    QLabel *label_134;
    QLabel *label_135;
    QLabel *label_136;
    QLabel *label_137;
    QLabel *label_138;
    QLabel *label_139;
    QLabel *label_141;
    QLineEdit *lineEdit_10;
    QLineEdit *lineEdit_11;
    QLineEdit *lineEdit_12;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QLineEdit *lineEdit_16;
    QLineEdit *lineEdit_17;
    QPushButton *pushButton_22;
    QLabel *label_142;
    QWidget *widget_2;
    QLabel *label;
    QLabel *label_6;
    QTextEdit *textEdit;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_16;
    QPushButton *pushButton_9;

    void setupUi(QMainWindow *Dashboard)
    {
        if (Dashboard->objectName().isEmpty())
            Dashboard->setObjectName("Dashboard");
        Dashboard->resize(1540, 800);
        Dashboard->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 59);"));
        centralwidget = new QWidget(Dashboard);
        centralwidget->setObjectName("centralwidget");
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(centralwidget->sizePolicy().hasHeightForWidth());
        centralwidget->setSizePolicy(sizePolicy);
        horizontalLayout = new QHBoxLayout(centralwidget);
        horizontalLayout->setObjectName("horizontalLayout");
        widget = new QWidget(centralwidget);
        widget->setObjectName("widget");
        widget->setMaximumSize(QSize(250, 800));
        widget->setStyleSheet(QString::fromUtf8(""));
        pushButton_3 = new QPushButton(widget);
        pushButton_3->setObjectName("pushButton_3");
        pushButton_3->setGeometry(QRect(-20, 60, 261, 71));
        pushButton_3->setAutoFillBackground(false);
        pushButton_3->setStyleSheet(QString::fromUtf8("background-color: rgb(145, 65, 217);\n"
"color: rgb(255, 255, 255);"));
        pushButton_3->setAutoDefault(false);
        pushButton_4 = new QPushButton(widget);
        pushButton_4->setObjectName("pushButton_4");
        pushButton_4->setGeometry(QRect(-20, 160, 261, 71));
        pushButton_4->setStyleSheet(QString::fromUtf8("background-color: rgb(38, 49, 115);\n"
"color: rgb(255, 255, 255);"));
        pushButton_5 = new QPushButton(widget);
        pushButton_5->setObjectName("pushButton_5");
        pushButton_5->setGeometry(QRect(-20, 260, 261, 71));
        pushButton_5->setStyleSheet(QString::fromUtf8("selection-background-color: rgb(0, 0, 255);"));
        label_5 = new QLabel(widget);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(-30, -30, 271, 831));
        label_5->setPixmap(QPixmap(QString::fromUtf8(":/side bar-PhotoRoom.png")));
        label_5->setScaledContents(true);
        label_7 = new QLabel(widget);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(20, 10, 131, 31));
        QFont font;
        font.setPointSize(12);
        font.setBold(true);
        label_7->setFont(font);
        label_7->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(45, 65, 124);"));
        pushButton_6 = new QPushButton(widget);
        pushButton_6->setObjectName("pushButton_6");
        pushButton_6->setGeometry(QRect(0, 360, 241, 71));
        pushButton_7 = new QPushButton(widget);
        pushButton_7->setObjectName("pushButton_7");
        pushButton_7->setGeometry(QRect(0, 460, 241, 71));
        label_5->raise();
        pushButton_3->raise();
        pushButton_4->raise();
        pushButton_5->raise();
        label_7->raise();
        pushButton_6->raise();
        pushButton_7->raise();

        horizontalLayout->addWidget(widget);

        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setMaximumSize(QSize(1040, 800));
        stackedWidget->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 59);"));
        page = new QWidget();
        page->setObjectName("page");
        pushButton = new QPushButton(page);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(10, 50, 41, 41));
        pushButton->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/menu-bar.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton->setIcon(icon);
        pushButton->setIconSize(QSize(80, 30));
        pushButton_2 = new QPushButton(page);
        pushButton_2->setObjectName("pushButton_2");
        pushButton_2->setGeometry(QRect(940, 50, 51, 41));
        pushButton_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/profile.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_2->setIcon(icon1);
        pushButton_2->setIconSize(QSize(80, 30));
        label_2 = new QLabel(page);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(300, 210, 131, 20));
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_8 = new QLabel(page);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(10, 0, 171, 31));
        QFont font1;
        font1.setPointSize(15);
        font1.setBold(true);
        label_8->setFont(font1);
        label_8->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        label_3 = new QLabel(page_2);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(170, 200, 191, 41));
        label_3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(page_2);
        page_5 = new QWidget();
        page_5->setObjectName("page_5");
        label_176 = new QLabel(page_5);
        label_176->setObjectName("label_176");
        label_176->setGeometry(QRect(450, 20, 151, 51));
        QFont font2;
        font2.setPointSize(24);
        font2.setBold(true);
        label_176->setFont(font2);
        label_176->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        stackedWidget_5 = new QStackedWidget(page_5);
        stackedWidget_5->setObjectName("stackedWidget_5");
        stackedWidget_5->setGeometry(QRect(9, 79, 1021, 691));
        page_18 = new QWidget();
        page_18->setObjectName("page_18");
        pushButton_23 = new QPushButton(page_18);
        pushButton_23->setObjectName("pushButton_23");
        pushButton_23->setGeometry(QRect(920, 10, 80, 24));
        QFont font3;
        font3.setBold(true);
        font3.setItalic(true);
        pushButton_23->setFont(font3);
        pushButton_23->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_177 = new QLabel(page_18);
        label_177->setObjectName("label_177");
        label_177->setGeometry(QRect(550, 150, 461, 391));
        label_177->setPixmap(QPixmap(QString::fromUtf8(":/AboutPyra.png")));
        label_177->setScaledContents(true);
        label_178 = new QLabel(page_18);
        label_178->setObjectName("label_178");
        label_178->setGeometry(QRect(20, 70, 521, 541));
        QFont font4;
        font4.setPointSize(11);
        label_178->setFont(font4);
        label_178->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_179 = new QLabel(page_18);
        label_179->setObjectName("label_179");
        label_179->setGeometry(QRect(20, 300, 161, 31));
        QFont font5;
        font5.setPointSize(14);
        font5.setBold(true);
        label_179->setFont(font5);
        label_179->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_180 = new QLabel(page_18);
        label_180->setObjectName("label_180");
        label_180->setGeometry(QRect(20, 400, 151, 31));
        label_180->setFont(font5);
        label_180->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_181 = new QLabel(page_18);
        label_181->setObjectName("label_181");
        label_181->setGeometry(QRect(20, 200, 71, 31));
        label_181->setFont(font5);
        label_181->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        stackedWidget_5->addWidget(page_18);
        page_19 = new QWidget();
        page_19->setObjectName("page_19");
        pushButton_24 = new QPushButton(page_19);
        pushButton_24->setObjectName("pushButton_24");
        pushButton_24->setGeometry(QRect(920, 10, 91, 21));
        QFont font6;
        font6.setPointSize(10);
        font6.setBold(true);
        font6.setItalic(true);
        pushButton_24->setFont(font6);
        pushButton_24->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_182 = new QLabel(page_19);
        label_182->setObjectName("label_182");
        label_182->setGeometry(QRect(350, 150, 49, 16));
        label_182->setPixmap(QPixmap(QString::fromUtf8(":/TimeLine.png")));
        label_182->setScaledContents(false);
        label_183 = new QLabel(page_19);
        label_183->setObjectName("label_183");
        label_183->setGeometry(QRect(410, 80, 211, 581));
        label_183->setPixmap(QPixmap(QString::fromUtf8(":/TimeLine.png")));
        label_183->setScaledContents(true);
        label_184 = new QLabel(page_19);
        label_184->setObjectName("label_184");
        label_184->setGeometry(QRect(340, 20, 341, 51));
        QFont font7;
        font7.setPointSize(20);
        font7.setBold(true);
        font7.setItalic(true);
        label_184->setFont(font7);
        label_184->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_185 = new QLabel(page_19);
        label_185->setObjectName("label_185");
        label_185->setGeometry(QRect(470, 120, 81, 41));
        QFont font8;
        font8.setPointSize(22);
        font8.setBold(true);
        label_185->setFont(font8);
        label_185->setAutoFillBackground(false);
        label_185->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(41, 109, 182);"));
        label_186 = new QLabel(page_19);
        label_186->setObjectName("label_186");
        label_186->setGeometry(QRect(470, 430, 81, 41));
        label_186->setFont(font8);
        label_186->setAutoFillBackground(false);
        label_186->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(41, 109, 182);"));
        label_187 = new QLabel(page_19);
        label_187->setObjectName("label_187");
        label_187->setGeometry(QRect(470, 270, 81, 41));
        label_187->setFont(font8);
        label_187->setAutoFillBackground(false);
        label_187->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(41, 109, 182);"));
        label_188 = new QLabel(page_19);
        label_188->setObjectName("label_188");
        label_188->setGeometry(QRect(660, 130, 321, 171));
        QFont font9;
        font9.setPointSize(11);
        font9.setBold(false);
        label_188->setFont(font9);
        label_188->setAutoFillBackground(false);
        label_188->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(41, 109, 182);"));
        label_188->setAlignment(Qt::AlignCenter);
        label_189 = new QLabel(page_19);
        label_189->setObjectName("label_189");
        label_189->setGeometry(QRect(660, 430, 321, 201));
        label_189->setFont(font9);
        label_189->setAutoFillBackground(false);
        label_189->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(41, 109, 182);"));
        label_189->setAlignment(Qt::AlignCenter);
        label_190 = new QLabel(page_19);
        label_190->setObjectName("label_190");
        label_190->setGeometry(QRect(70, 280, 321, 171));
        label_190->setFont(font9);
        label_190->setAutoFillBackground(false);
        label_190->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(41, 109, 182);"));
        label_190->setAlignment(Qt::AlignCenter);
        stackedWidget_5->addWidget(page_19);
        stackedWidget->addWidget(page_5);
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        label_9 = new QLabel(page_4);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(250, 140, 211, 41));
        label_9->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_10 = new QLabel(page_4);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(260, 250, 91, 20));
        label_10->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_11 = new QLabel(page_4);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(50, 290, 63, 20));
        label_11->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_12 = new QLabel(page_4);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(120, 280, 251, 31));
        label_12->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_13 = new QLabel(page_4);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(500, 280, 121, 20));
        label_13->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_14 = new QLabel(page_4);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(630, 270, 291, 31));
        label_14->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_15 = new QLabel(page_4);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(50, 340, 91, 41));
        label_15->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_20 = new QLabel(page_4);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(50, 480, 63, 20));
        label_20->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_21 = new QLabel(page_4);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(120, 470, 151, 41));
        label_21->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        textEdit_2 = new QTextEdit(page_4);
        textEdit_2->setObjectName("textEdit_2");
        textEdit_2->setGeometry(QRect(170, 350, 651, 61));
        textEdit_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_22 = new QLabel(page_4);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(10, 70, 231, 171));
        label_22->setScaledContents(true);
        pushButton_8 = new QPushButton(page_4);
        pushButton_8->setObjectName("pushButton_8");
        pushButton_8->setGeometry(QRect(170, 40, 141, 21));
        pushButton_8->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pushButton_10 = new QPushButton(page_4);
        pushButton_10->setObjectName("pushButton_10");
        pushButton_10->setGeometry(QRect(830, 380, 83, 29));
        pushButton_10->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lineEdit = new QLineEdit(page_4);
        lineEdit->setObjectName("lineEdit");
        lineEdit->setGeometry(QRect(170, 350, 651, 61));
        lineEdit->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        comboBox = new QComboBox(page_4);
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->setObjectName("comboBox");
        comboBox->setGeometry(QRect(120, 470, 151, 41));
        comboBox->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lineEdit_2 = new QLineEdit(page_4);
        lineEdit_2->setObjectName("lineEdit_2");
        lineEdit_2->setGeometry(QRect(120, 280, 241, 28));
        lineEdit_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lineEdit_3 = new QLineEdit(page_4);
        lineEdit_3->setObjectName("lineEdit_3");
        lineEdit_3->setGeometry(QRect(630, 270, 281, 31));
        lineEdit_3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lineEdit_4 = new QLineEdit(page_4);
        lineEdit_4->setObjectName("lineEdit_4");
        lineEdit_4->setGeometry(QRect(250, 150, 211, 31));
        lineEdit_4->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pushButton_11 = new QPushButton(page_4);
        pushButton_11->setObjectName("pushButton_11");
        pushButton_11->setGeometry(QRect(300, 480, 83, 29));
        pushButton_11->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pushButton_12 = new QPushButton(page_4);
        pushButton_12->setObjectName("pushButton_12");
        pushButton_12->setGeometry(QRect(940, 270, 83, 29));
        pushButton_12->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pushButton_13 = new QPushButton(page_4);
        pushButton_13->setObjectName("pushButton_13");
        pushButton_13->setGeometry(QRect(380, 280, 83, 29));
        pushButton_13->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pushButton_14 = new QPushButton(page_4);
        pushButton_14->setObjectName("pushButton_14");
        pushButton_14->setGeometry(QRect(470, 150, 83, 29));
        pushButton_14->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_24 = new QLabel(page_4);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(10, 20, 981, 221));
        label_24->setPixmap(QPixmap(QString::fromUtf8(":/profile_cover.jpg")));
        label_24->setScaledContents(true);
        stackedWidget_2 = new QStackedWidget(page_4);
        stackedWidget_2->setObjectName("stackedWidget_2");
        stackedWidget_2->setGeometry(QRect(30, 520, 951, 111));
        stackedWidget_2->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        page_6 = new QWidget();
        page_6->setObjectName("page_6");
        label_25 = new QLabel(page_6);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(10, 0, 161, 111));
        label_25->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_26 = new QLabel(page_6);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(10, 0, 171, 111));
        label_26->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_27 = new QLabel(page_6);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(210, 0, 151, 111));
        label_27->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_28 = new QLabel(page_6);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(210, 0, 151, 111));
        label_28->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_29 = new QLabel(page_6);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(380, 0, 151, 111));
        label_29->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_30 = new QLabel(page_6);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(380, 0, 151, 111));
        label_30->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_31 = new QLabel(page_6);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(570, 0, 151, 111));
        label_31->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_32 = new QLabel(page_6);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(570, 0, 151, 111));
        label_32->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_33 = new QLabel(page_6);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(770, 0, 141, 111));
        label_33->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_34 = new QLabel(page_6);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(770, 0, 141, 111));
        label_34->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_145 = new QLabel(page_6);
        label_145->setObjectName("label_145");
        label_145->setGeometry(QRect(122, 87, 51, 20));
        QFont font10;
        font10.setFamilies({QString::fromUtf8("Palatino Linotype")});
        label_145->setFont(font10);
        label_145->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_144 = new QLabel(page_6);
        label_144->setObjectName("label_144");
        label_144->setGeometry(QRect(110, 67, 51, 20));
        label_144->setFont(font10);
        label_144->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_140 = new QLabel(page_6);
        label_140->setObjectName("label_140");
        label_140->setGeometry(QRect(10, 65, 91, 20));
        QFont font11;
        font11.setFamilies({QString::fromUtf8("Palatino Linotype")});
        font11.setPointSize(10);
        label_140->setFont(font11);
        label_140->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_143 = new QLabel(page_6);
        label_143->setObjectName("label_143");
        label_143->setGeometry(QRect(10, 87, 31, 20));
        QFont font12;
        font12.setFamilies({QString::fromUtf8("Palatino Linotype")});
        font12.setPointSize(12);
        label_143->setFont(font12);
        label_143->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_147 = new QLabel(page_6);
        label_147->setObjectName("label_147");
        label_147->setGeometry(QRect(40, 87, 81, 20));
        label_147->setFont(font12);
        label_147->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_146 = new QLabel(page_6);
        label_146->setObjectName("label_146");
        label_146->setGeometry(QRect(10, 0, 161, 41));
        label_146->setScaledContents(true);
        label_23 = new QLabel(page_6);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(10, 40, 151, 20));
        label_23->setFont(font11);
        label_23->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_149 = new QLabel(page_6);
        label_149->setObjectName("label_149");
        label_149->setGeometry(QRect(210, 43, 151, 20));
        label_149->setFont(font11);
        label_149->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_154 = new QLabel(page_6);
        label_154->setObjectName("label_154");
        label_154->setGeometry(QRect(310, 90, 51, 20));
        label_154->setFont(font10);
        label_154->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_152 = new QLabel(page_6);
        label_152->setObjectName("label_152");
        label_152->setGeometry(QRect(210, 90, 31, 20));
        label_152->setFont(font12);
        label_152->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_148 = new QLabel(page_6);
        label_148->setObjectName("label_148");
        label_148->setGeometry(QRect(210, 0, 151, 41));
        label_148->setScaledContents(true);
        label_153 = new QLabel(page_6);
        label_153->setObjectName("label_153");
        label_153->setGeometry(QRect(240, 90, 61, 20));
        label_153->setFont(font12);
        label_153->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_150 = new QLabel(page_6);
        label_150->setObjectName("label_150");
        label_150->setGeometry(QRect(210, 68, 91, 20));
        label_150->setFont(font11);
        label_150->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_151 = new QLabel(page_6);
        label_151->setObjectName("label_151");
        label_151->setGeometry(QRect(310, 70, 51, 20));
        label_151->setFont(font10);
        label_151->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_158 = new QLabel(page_6);
        label_158->setObjectName("label_158");
        label_158->setGeometry(QRect(480, 70, 51, 20));
        label_158->setFont(font10);
        label_158->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_160 = new QLabel(page_6);
        label_160->setObjectName("label_160");
        label_160->setGeometry(QRect(410, 90, 61, 20));
        label_160->setFont(font12);
        label_160->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_157 = new QLabel(page_6);
        label_157->setObjectName("label_157");
        label_157->setGeometry(QRect(380, 68, 91, 20));
        label_157->setFont(font11);
        label_157->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_161 = new QLabel(page_6);
        label_161->setObjectName("label_161");
        label_161->setGeometry(QRect(480, 90, 51, 20));
        label_161->setFont(font10);
        label_161->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_156 = new QLabel(page_6);
        label_156->setObjectName("label_156");
        label_156->setGeometry(QRect(380, 43, 151, 20));
        label_156->setFont(font11);
        label_156->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_155 = new QLabel(page_6);
        label_155->setObjectName("label_155");
        label_155->setGeometry(QRect(380, 0, 151, 41));
        label_155->setScaledContents(true);
        label_159 = new QLabel(page_6);
        label_159->setObjectName("label_159");
        label_159->setGeometry(QRect(380, 90, 31, 20));
        label_159->setFont(font12);
        label_159->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_164 = new QLabel(page_6);
        label_164->setObjectName("label_164");
        label_164->setGeometry(QRect(570, 65, 91, 20));
        label_164->setFont(font11);
        label_164->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_168 = new QLabel(page_6);
        label_168->setObjectName("label_168");
        label_168->setGeometry(QRect(670, 87, 51, 20));
        label_168->setFont(font10);
        label_168->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_166 = new QLabel(page_6);
        label_166->setObjectName("label_166");
        label_166->setGeometry(QRect(570, 87, 31, 20));
        label_166->setFont(font12);
        label_166->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_165 = new QLabel(page_6);
        label_165->setObjectName("label_165");
        label_165->setGeometry(QRect(670, 67, 51, 20));
        label_165->setFont(font10);
        label_165->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_167 = new QLabel(page_6);
        label_167->setObjectName("label_167");
        label_167->setGeometry(QRect(600, 87, 61, 20));
        label_167->setFont(font12);
        label_167->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_162 = new QLabel(page_6);
        label_162->setObjectName("label_162");
        label_162->setGeometry(QRect(570, -3, 151, 41));
        label_162->setScaledContents(true);
        label_163 = new QLabel(page_6);
        label_163->setObjectName("label_163");
        label_163->setGeometry(QRect(570, 40, 151, 20));
        label_163->setFont(font11);
        label_163->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_170 = new QLabel(page_6);
        label_170->setObjectName("label_170");
        label_170->setGeometry(QRect(770, 43, 141, 20));
        label_170->setFont(font11);
        label_170->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_173 = new QLabel(page_6);
        label_173->setObjectName("label_173");
        label_173->setGeometry(QRect(770, 90, 31, 20));
        label_173->setFont(font12);
        label_173->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_174 = new QLabel(page_6);
        label_174->setObjectName("label_174");
        label_174->setGeometry(QRect(800, 90, 61, 20));
        label_174->setFont(font12);
        label_174->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_172 = new QLabel(page_6);
        label_172->setObjectName("label_172");
        label_172->setGeometry(QRect(870, 70, 41, 20));
        label_172->setFont(font10);
        label_172->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_171 = new QLabel(page_6);
        label_171->setObjectName("label_171");
        label_171->setGeometry(QRect(770, 68, 91, 20));
        label_171->setFont(font11);
        label_171->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        label_169 = new QLabel(page_6);
        label_169->setObjectName("label_169");
        label_169->setGeometry(QRect(770, 0, 141, 41));
        label_169->setScaledContents(true);
        label_175 = new QLabel(page_6);
        label_175->setObjectName("label_175");
        label_175->setGeometry(QRect(870, 90, 41, 20));
        label_175->setFont(font10);
        label_175->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 65, 135);"));
        stackedWidget_2->addWidget(page_6);
        label_25->raise();
        label_27->raise();
        label_29->raise();
        label_31->raise();
        label_33->raise();
        label_145->raise();
        label_144->raise();
        label_140->raise();
        label_143->raise();
        label_147->raise();
        label_146->raise();
        label_23->raise();
        label_149->raise();
        label_154->raise();
        label_152->raise();
        label_148->raise();
        label_153->raise();
        label_150->raise();
        label_151->raise();
        label_158->raise();
        label_160->raise();
        label_157->raise();
        label_161->raise();
        label_156->raise();
        label_155->raise();
        label_159->raise();
        label_164->raise();
        label_168->raise();
        label_166->raise();
        label_165->raise();
        label_167->raise();
        label_162->raise();
        label_163->raise();
        label_170->raise();
        label_173->raise();
        label_174->raise();
        label_172->raise();
        label_171->raise();
        label_175->raise();
        label_169->raise();
        label_34->raise();
        label_32->raise();
        label_30->raise();
        label_28->raise();
        label_26->raise();
        page_7 = new QWidget();
        page_7->setObjectName("page_7");
        label_35 = new QLabel(page_7);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(20, 20, 131, 81));
        label_35->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_36 = new QLabel(page_7);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(50, 40, 61, 41));
        label_36->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_37 = new QLabel(page_7);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(170, 20, 131, 81));
        label_37->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_38 = new QLabel(page_7);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(200, 40, 61, 41));
        label_38->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_39 = new QLabel(page_7);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(320, 20, 131, 81));
        label_39->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_40 = new QLabel(page_7);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(360, 40, 61, 41));
        label_40->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_41 = new QLabel(page_7);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(470, 20, 131, 81));
        label_41->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_42 = new QLabel(page_7);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(500, 40, 61, 41));
        label_42->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_43 = new QLabel(page_7);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(620, 20, 131, 81));
        label_43->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_44 = new QLabel(page_7);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(650, 40, 61, 41));
        label_44->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        stackedWidget_2->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName("page_8");
        label_45 = new QLabel(page_8);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(30, 10, 131, 81));
        label_45->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_46 = new QLabel(page_8);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(60, 40, 61, 41));
        label_46->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_47 = new QLabel(page_8);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(180, 10, 131, 81));
        label_47->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_48 = new QLabel(page_8);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(220, 30, 61, 41));
        label_48->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_49 = new QLabel(page_8);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(330, 10, 131, 81));
        label_49->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_50 = new QLabel(page_8);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(370, 40, 61, 41));
        label_50->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_51 = new QLabel(page_8);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(480, 10, 131, 81));
        label_51->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_52 = new QLabel(page_8);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(520, 30, 61, 41));
        label_52->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_53 = new QLabel(page_8);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(630, 10, 131, 81));
        label_53->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_54 = new QLabel(page_8);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(670, 30, 61, 41));
        label_54->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        stackedWidget_2->addWidget(page_8);
        page_9 = new QWidget();
        page_9->setObjectName("page_9");
        label_55 = new QLabel(page_9);
        label_55->setObjectName("label_55");
        label_55->setGeometry(QRect(30, 10, 131, 81));
        label_55->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_56 = new QLabel(page_9);
        label_56->setObjectName("label_56");
        label_56->setGeometry(QRect(60, 30, 61, 41));
        label_56->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_57 = new QLabel(page_9);
        label_57->setObjectName("label_57");
        label_57->setGeometry(QRect(180, 10, 131, 81));
        label_57->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_58 = new QLabel(page_9);
        label_58->setObjectName("label_58");
        label_58->setGeometry(QRect(210, 30, 61, 41));
        label_58->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_59 = new QLabel(page_9);
        label_59->setObjectName("label_59");
        label_59->setGeometry(QRect(330, 10, 131, 81));
        label_59->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_60 = new QLabel(page_9);
        label_60->setObjectName("label_60");
        label_60->setGeometry(QRect(360, 30, 61, 41));
        label_60->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_61 = new QLabel(page_9);
        label_61->setObjectName("label_61");
        label_61->setGeometry(QRect(480, 10, 131, 81));
        label_61->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_62 = new QLabel(page_9);
        label_62->setObjectName("label_62");
        label_62->setGeometry(QRect(520, 30, 61, 41));
        label_62->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_63 = new QLabel(page_9);
        label_63->setObjectName("label_63");
        label_63->setGeometry(QRect(630, 10, 131, 81));
        label_63->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_64 = new QLabel(page_9);
        label_64->setObjectName("label_64");
        label_64->setGeometry(QRect(670, 40, 61, 41));
        label_64->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        stackedWidget_2->addWidget(page_9);
        page_10 = new QWidget();
        page_10->setObjectName("page_10");
        label_65 = new QLabel(page_10);
        label_65->setObjectName("label_65");
        label_65->setGeometry(QRect(10, 0, 161, 121));
        label_65->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_66 = new QLabel(page_10);
        label_66->setObjectName("label_66");
        label_66->setGeometry(QRect(170, 30, 61, 41));
        label_66->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_67 = new QLabel(page_10);
        label_67->setObjectName("label_67");
        label_67->setGeometry(QRect(210, 0, 151, 111));
        label_67->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_68 = new QLabel(page_10);
        label_68->setObjectName("label_68");
        label_68->setGeometry(QRect(330, 40, 61, 41));
        label_68->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_69 = new QLabel(page_10);
        label_69->setObjectName("label_69");
        label_69->setGeometry(QRect(380, 0, 151, 121));
        label_69->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_70 = new QLabel(page_10);
        label_70->setObjectName("label_70");
        label_70->setGeometry(QRect(510, 30, 61, 41));
        label_70->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_71 = new QLabel(page_10);
        label_71->setObjectName("label_71");
        label_71->setGeometry(QRect(570, 0, 151, 121));
        label_71->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_72 = new QLabel(page_10);
        label_72->setObjectName("label_72");
        label_72->setGeometry(QRect(700, 30, 61, 41));
        label_72->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_73 = new QLabel(page_10);
        label_73->setObjectName("label_73");
        label_73->setGeometry(QRect(770, 0, 141, 121));
        label_73->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_74 = new QLabel(page_10);
        label_74->setObjectName("label_74");
        label_74->setGeometry(QRect(900, 30, 61, 41));
        label_74->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        stackedWidget_2->addWidget(page_10);
        stackedWidget_3 = new QStackedWidget(page_4);
        stackedWidget_3->setObjectName("stackedWidget_3");
        stackedWidget_3->setGeometry(QRect(30, 660, 951, 111));
        stackedWidget_3->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);\n"
""));
        page_11 = new QWidget();
        page_11->setObjectName("page_11");
        label_75 = new QLabel(page_11);
        label_75->setObjectName("label_75");
        label_75->setGeometry(QRect(10, 0, 161, 111));
        label_75->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_76 = new QLabel(page_11);
        label_76->setObjectName("label_76");
        label_76->setGeometry(QRect(10, 0, 161, 111));
        label_76->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_77 = new QLabel(page_11);
        label_77->setObjectName("label_77");
        label_77->setGeometry(QRect(210, 0, 151, 121));
        label_77->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_78 = new QLabel(page_11);
        label_78->setObjectName("label_78");
        label_78->setGeometry(QRect(210, 0, 151, 121));
        label_78->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_79 = new QLabel(page_11);
        label_79->setObjectName("label_79");
        label_79->setGeometry(QRect(380, 0, 151, 111));
        label_79->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_80 = new QLabel(page_11);
        label_80->setObjectName("label_80");
        label_80->setGeometry(QRect(380, 0, 151, 111));
        label_80->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_81 = new QLabel(page_11);
        label_81->setObjectName("label_81");
        label_81->setGeometry(QRect(570, 0, 151, 111));
        label_81->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_82 = new QLabel(page_11);
        label_82->setObjectName("label_82");
        label_82->setGeometry(QRect(570, 0, 151, 111));
        label_82->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        label_83 = new QLabel(page_11);
        label_83->setObjectName("label_83");
        label_83->setGeometry(QRect(770, 0, 141, 111));
        label_83->setStyleSheet(QString::fromUtf8("background-color: rgb(51, 65, 135);"));
        label_84 = new QLabel(page_11);
        label_84->setObjectName("label_84");
        label_84->setGeometry(QRect(770, 0, 141, 111));
        label_84->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 21, 83);"));
        stackedWidget_3->addWidget(page_11);
        page_12 = new QWidget();
        page_12->setObjectName("page_12");
        label_85 = new QLabel(page_12);
        label_85->setObjectName("label_85");
        label_85->setGeometry(QRect(20, 20, 131, 81));
        label_85->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_86 = new QLabel(page_12);
        label_86->setObjectName("label_86");
        label_86->setGeometry(QRect(50, 40, 61, 41));
        label_86->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_87 = new QLabel(page_12);
        label_87->setObjectName("label_87");
        label_87->setGeometry(QRect(170, 20, 131, 81));
        label_87->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_88 = new QLabel(page_12);
        label_88->setObjectName("label_88");
        label_88->setGeometry(QRect(200, 40, 61, 41));
        label_88->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_89 = new QLabel(page_12);
        label_89->setObjectName("label_89");
        label_89->setGeometry(QRect(320, 20, 131, 81));
        label_89->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_90 = new QLabel(page_12);
        label_90->setObjectName("label_90");
        label_90->setGeometry(QRect(360, 40, 61, 41));
        label_90->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_91 = new QLabel(page_12);
        label_91->setObjectName("label_91");
        label_91->setGeometry(QRect(470, 20, 131, 81));
        label_91->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_92 = new QLabel(page_12);
        label_92->setObjectName("label_92");
        label_92->setGeometry(QRect(500, 40, 61, 41));
        label_92->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_93 = new QLabel(page_12);
        label_93->setObjectName("label_93");
        label_93->setGeometry(QRect(620, 20, 131, 81));
        label_93->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_94 = new QLabel(page_12);
        label_94->setObjectName("label_94");
        label_94->setGeometry(QRect(650, 40, 61, 41));
        label_94->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        stackedWidget_3->addWidget(page_12);
        page_13 = new QWidget();
        page_13->setObjectName("page_13");
        label_95 = new QLabel(page_13);
        label_95->setObjectName("label_95");
        label_95->setGeometry(QRect(30, 10, 131, 81));
        label_95->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_96 = new QLabel(page_13);
        label_96->setObjectName("label_96");
        label_96->setGeometry(QRect(60, 40, 61, 41));
        label_96->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_97 = new QLabel(page_13);
        label_97->setObjectName("label_97");
        label_97->setGeometry(QRect(180, 10, 131, 81));
        label_97->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_98 = new QLabel(page_13);
        label_98->setObjectName("label_98");
        label_98->setGeometry(QRect(220, 30, 61, 41));
        label_98->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_99 = new QLabel(page_13);
        label_99->setObjectName("label_99");
        label_99->setGeometry(QRect(330, 10, 131, 81));
        label_99->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_100 = new QLabel(page_13);
        label_100->setObjectName("label_100");
        label_100->setGeometry(QRect(370, 40, 61, 41));
        label_100->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_101 = new QLabel(page_13);
        label_101->setObjectName("label_101");
        label_101->setGeometry(QRect(480, 10, 131, 81));
        label_101->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_102 = new QLabel(page_13);
        label_102->setObjectName("label_102");
        label_102->setGeometry(QRect(520, 30, 61, 41));
        label_102->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_103 = new QLabel(page_13);
        label_103->setObjectName("label_103");
        label_103->setGeometry(QRect(630, 10, 131, 81));
        label_103->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_104 = new QLabel(page_13);
        label_104->setObjectName("label_104");
        label_104->setGeometry(QRect(670, 30, 61, 41));
        label_104->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        stackedWidget_3->addWidget(page_13);
        page_14 = new QWidget();
        page_14->setObjectName("page_14");
        label_105 = new QLabel(page_14);
        label_105->setObjectName("label_105");
        label_105->setGeometry(QRect(30, 10, 131, 81));
        label_105->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_106 = new QLabel(page_14);
        label_106->setObjectName("label_106");
        label_106->setGeometry(QRect(60, 30, 61, 41));
        label_106->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_107 = new QLabel(page_14);
        label_107->setObjectName("label_107");
        label_107->setGeometry(QRect(180, 10, 131, 81));
        label_107->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_108 = new QLabel(page_14);
        label_108->setObjectName("label_108");
        label_108->setGeometry(QRect(210, 30, 61, 41));
        label_108->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_109 = new QLabel(page_14);
        label_109->setObjectName("label_109");
        label_109->setGeometry(QRect(330, 10, 131, 81));
        label_109->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_110 = new QLabel(page_14);
        label_110->setObjectName("label_110");
        label_110->setGeometry(QRect(360, 30, 61, 41));
        label_110->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_111 = new QLabel(page_14);
        label_111->setObjectName("label_111");
        label_111->setGeometry(QRect(480, 10, 131, 81));
        label_111->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_112 = new QLabel(page_14);
        label_112->setObjectName("label_112");
        label_112->setGeometry(QRect(520, 30, 61, 41));
        label_112->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_113 = new QLabel(page_14);
        label_113->setObjectName("label_113");
        label_113->setGeometry(QRect(630, 10, 131, 81));
        label_113->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_114 = new QLabel(page_14);
        label_114->setObjectName("label_114");
        label_114->setGeometry(QRect(670, 40, 61, 41));
        label_114->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        stackedWidget_3->addWidget(page_14);
        page_15 = new QWidget();
        page_15->setObjectName("page_15");
        label_115 = new QLabel(page_15);
        label_115->setObjectName("label_115");
        label_115->setGeometry(QRect(30, 10, 131, 81));
        label_115->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_116 = new QLabel(page_15);
        label_116->setObjectName("label_116");
        label_116->setGeometry(QRect(60, 30, 61, 41));
        label_116->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_117 = new QLabel(page_15);
        label_117->setObjectName("label_117");
        label_117->setGeometry(QRect(190, 10, 131, 81));
        label_117->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_118 = new QLabel(page_15);
        label_118->setObjectName("label_118");
        label_118->setGeometry(QRect(220, 30, 61, 41));
        label_118->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_119 = new QLabel(page_15);
        label_119->setObjectName("label_119");
        label_119->setGeometry(QRect(340, 10, 131, 81));
        label_119->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_120 = new QLabel(page_15);
        label_120->setObjectName("label_120");
        label_120->setGeometry(QRect(370, 30, 61, 41));
        label_120->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_121 = new QLabel(page_15);
        label_121->setObjectName("label_121");
        label_121->setGeometry(QRect(490, 10, 131, 81));
        label_121->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_122 = new QLabel(page_15);
        label_122->setObjectName("label_122");
        label_122->setGeometry(QRect(530, 30, 61, 41));
        label_122->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        label_123 = new QLabel(page_15);
        label_123->setObjectName("label_123");
        label_123->setGeometry(QRect(640, 10, 131, 81));
        label_123->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 170, 255);"));
        label_124 = new QLabel(page_15);
        label_124->setObjectName("label_124");
        label_124->setGeometry(QRect(670, 30, 61, 41));
        label_124->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 255);"));
        stackedWidget_3->addWidget(page_15);
        pushButton_15 = new QPushButton(page_4);
        pushButton_15->setObjectName("pushButton_15");
        pushButton_15->setGeometry(QRect(910, 480, 83, 29));
        pushButton_15->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pushButton_16 = new QPushButton(page_4);
        pushButton_16->setObjectName("pushButton_16");
        pushButton_16->setGeometry(QRect(810, 480, 83, 29));
        pushButton_16->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pushButton_17 = new QPushButton(page_4);
        pushButton_17->setObjectName("pushButton_17");
        pushButton_17->setGeometry(QRect(600, 480, 83, 29));
        pushButton_17->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        pushButton_18 = new QPushButton(page_4);
        pushButton_18->setObjectName("pushButton_18");
        pushButton_18->setGeometry(QRect(510, 480, 83, 29));
        pushButton_18->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_128 = new QLabel(page_4);
        label_128->setObjectName("label_128");
        label_128->setGeometry(QRect(40, 440, 49, 16));
        label_128->setStyleSheet(QString::fromUtf8("font: 9pt \"Segoe UI\";\n"
"font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_129 = new QLabel(page_4);
        label_129->setObjectName("label_129");
        label_129->setGeometry(QRect(480, 440, 49, 16));
        label_129->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_130 = new QLabel(page_4);
        label_130->setObjectName("label_130");
        label_130->setGeometry(QRect(110, 430, 251, 31));
        label_130->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_131 = new QLabel(page_4);
        label_131->setObjectName("label_131");
        label_131->setGeometry(QRect(550, 430, 271, 31));
        label_131->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        pushButton_20 = new QPushButton(page_4);
        pushButton_20->setObjectName("pushButton_20");
        pushButton_20->setGeometry(QRect(390, 430, 80, 24));
        pushButton_20->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        pushButton_21 = new QPushButton(page_4);
        pushButton_21->setObjectName("pushButton_21");
        pushButton_21->setGeometry(QRect(840, 430, 80, 24));
        pushButton_21->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        lineEdit_8 = new QLineEdit(page_4);
        lineEdit_8->setObjectName("lineEdit_8");
        lineEdit_8->setGeometry(QRect(110, 430, 251, 24));
        lineEdit_8->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        lineEdit_9 = new QLineEdit(page_4);
        lineEdit_9->setObjectName("lineEdit_9");
        lineEdit_9->setGeometry(QRect(550, 430, 271, 31));
        lineEdit_9->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        stackedWidget->addWidget(page_4);
        lineEdit_9->raise();
        lineEdit_8->raise();
        label_24->raise();
        label_22->raise();
        lineEdit_2->raise();
        label_12->raise();
        comboBox->raise();
        label_21->raise();
        lineEdit_3->raise();
        label_14->raise();
        lineEdit_4->raise();
        label_9->raise();
        lineEdit->raise();
        label_10->raise();
        label_11->raise();
        label_13->raise();
        label_15->raise();
        label_20->raise();
        textEdit_2->raise();
        pushButton_8->raise();
        pushButton_14->raise();
        pushButton_12->raise();
        pushButton_13->raise();
        pushButton_10->raise();
        pushButton_11->raise();
        stackedWidget_2->raise();
        stackedWidget_3->raise();
        pushButton_15->raise();
        pushButton_16->raise();
        pushButton_17->raise();
        pushButton_18->raise();
        label_128->raise();
        label_129->raise();
        label_130->raise();
        label_131->raise();
        pushButton_20->raise();
        pushButton_21->raise();
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        label_4 = new QLabel(page_3);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(290, 180, 131, 81));
        label_4->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        stackedWidget_4 = new QStackedWidget(page_3);
        stackedWidget_4->setObjectName("stackedWidget_4");
        stackedWidget_4->setGeometry(QRect(10, 0, 981, 721));
        page_16 = new QWidget();
        page_16->setObjectName("page_16");
        label_125 = new QLabel(page_16);
        label_125->setObjectName("label_125");
        label_125->setGeometry(QRect(130, 190, 81, 31));
        QFont font13;
        font13.setFamilies({QString::fromUtf8("Segoe UI")});
        font13.setPointSize(10);
        font13.setBold(false);
        font13.setItalic(false);
        label_125->setFont(font13);
        label_125->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lineEdit_5 = new QLineEdit(page_16);
        lineEdit_5->setObjectName("lineEdit_5");
        lineEdit_5->setGeometry(QRect(280, 190, 231, 31));
        lineEdit_5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        pushButton_19 = new QPushButton(page_16);
        pushButton_19->setObjectName("pushButton_19");
        pushButton_19->setGeometry(QRect(350, 470, 141, 31));
        pushButton_19->setStyleSheet(QString::fromUtf8("font: 16pt \"Segoe UI\";\n"
"font: 14pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Segoe UI\";"));
        label_126 = new QLabel(page_16);
        label_126->setObjectName("label_126");
        label_126->setGeometry(QRect(120, 250, 131, 20));
        label_126->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        lineEdit_6 = new QLineEdit(page_16);
        lineEdit_6->setObjectName("lineEdit_6");
        lineEdit_6->setGeometry(QRect(280, 250, 231, 31));
        lineEdit_6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_7 = new QLineEdit(page_16);
        lineEdit_7->setObjectName("lineEdit_7");
        lineEdit_7->setGeometry(QRect(280, 320, 401, 101));
        lineEdit_7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label_127 = new QLabel(page_16);
        label_127->setObjectName("label_127");
        label_127->setGeometry(QRect(120, 320, 111, 20));
        label_127->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_132 = new QLabel(page_16);
        label_132->setObjectName("label_132");
        label_132->setGeometry(QRect(120, 30, 741, 61));
        label_132->setStyleSheet(QString::fromUtf8("font: 16pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"font: 24pt \"Segoe UI\";"));
        stackedWidget_4->addWidget(page_16);
        page_17 = new QWidget();
        page_17->setObjectName("page_17");
        comboBox_2 = new QComboBox(page_17);
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->setObjectName("comboBox_2");
        comboBox_2->setGeometry(QRect(210, 120, 191, 31));
        comboBox_2->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"background-color: rgb(27, 27, 109);\n"
"background-color: rgb(30, 30, 120);\n"
"color: rgb(255, 255, 255);"));
        label_133 = new QLabel(page_17);
        label_133->setObjectName("label_133");
        label_133->setGeometry(QRect(480, 120, 71, 21));
        label_133->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_134 = new QLabel(page_17);
        label_134->setObjectName("label_134");
        label_134->setGeometry(QRect(70, 120, 121, 31));
        label_134->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_135 = new QLabel(page_17);
        label_135->setObjectName("label_135");
        label_135->setGeometry(QRect(70, 200, 161, 31));
        label_135->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_136 = new QLabel(page_17);
        label_136->setObjectName("label_136");
        label_136->setGeometry(QRect(510, 390, 71, 21));
        label_136->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"font: 11pt \"Segoe UI\";\n"
"font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_137 = new QLabel(page_17);
        label_137->setObjectName("label_137");
        label_137->setGeometry(QRect(430, 190, 131, 31));
        label_137->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_138 = new QLabel(page_17);
        label_138->setObjectName("label_138");
        label_138->setGeometry(QRect(70, 270, 71, 21));
        label_138->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_139 = new QLabel(page_17);
        label_139->setObjectName("label_139");
        label_139->setGeometry(QRect(460, 270, 91, 21));
        label_139->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        label_141 = new QLabel(page_17);
        label_141->setObjectName("label_141");
        label_141->setGeometry(QRect(70, 350, 111, 21));
        label_141->setStyleSheet(QString::fromUtf8("font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"));
        lineEdit_10 = new QLineEdit(page_17);
        lineEdit_10->setObjectName("lineEdit_10");
        lineEdit_10->setGeometry(QRect(250, 200, 101, 31));
        lineEdit_10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_11 = new QLineEdit(page_17);
        lineEdit_11->setObjectName("lineEdit_11");
        lineEdit_11->setGeometry(QRect(570, 420, 191, 31));
        lineEdit_11->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_12 = new QLineEdit(page_17);
        lineEdit_12->setObjectName("lineEdit_12");
        lineEdit_12->setGeometry(QRect(560, 190, 191, 31));
        lineEdit_12->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_13 = new QLineEdit(page_17);
        lineEdit_13->setObjectName("lineEdit_13");
        lineEdit_13->setGeometry(QRect(210, 270, 191, 31));
        lineEdit_13->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_14 = new QLineEdit(page_17);
        lineEdit_14->setObjectName("lineEdit_14");
        lineEdit_14->setGeometry(QRect(560, 270, 211, 31));
        lineEdit_14->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_16 = new QLineEdit(page_17);
        lineEdit_16->setObjectName("lineEdit_16");
        lineEdit_16->setGeometry(QRect(560, 120, 191, 31));
        lineEdit_16->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        lineEdit_17 = new QLineEdit(page_17);
        lineEdit_17->setObjectName("lineEdit_17");
        lineEdit_17->setGeometry(QRect(210, 340, 271, 141));
        lineEdit_17->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        pushButton_22 = new QPushButton(page_17);
        pushButton_22->setObjectName("pushButton_22");
        pushButton_22->setGeometry(QRect(380, 530, 141, 41));
        pushButton_22->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 90);"));
        label_142 = new QLabel(page_17);
        label_142->setObjectName("label_142");
        label_142->setGeometry(QRect(290, -10, 401, 61));
        label_142->setStyleSheet(QString::fromUtf8("font: 22pt \"Segoe UI\";\n"
"color: rgb(248, 248, 248);"));
        stackedWidget_4->addWidget(page_17);
        stackedWidget->addWidget(page_3);

        horizontalLayout->addWidget(stackedWidget);

        widget_2 = new QWidget(centralwidget);
        widget_2->setObjectName("widget_2");
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Maximum);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(widget_2->sizePolicy().hasHeightForWidth());
        widget_2->setSizePolicy(sizePolicy1);
        widget_2->setMaximumSize(QSize(250, 800));
        widget_2->setSizeIncrement(QSize(0, 0));
        widget_2->setStyleSheet(QString::fromUtf8("background-color: rgb(39, 0, 58);"));
        label = new QLabel(widget_2);
        label->setObjectName("label");
        label->setGeometry(QRect(40, 100, 171, 21));
        QFont font14;
        font14.setPointSize(11);
        font14.setBold(true);
        label->setFont(font14);
        label->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(142, 68, 217);"));
        label_6 = new QLabel(widget_2);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(-18, -21, 301, 821));
        label_6->setPixmap(QPixmap(QString::fromUtf8(":/side bar-PhotoRoom.png")));
        label_6->setScaledContents(true);
        textEdit = new QTextEdit(widget_2);
        textEdit->setObjectName("textEdit");
        textEdit->setGeometry(QRect(10, 200, 201, 151));
        textEdit->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_17 = new QLabel(widget_2);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(10, 160, 91, 21));
        label_17->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_18 = new QLabel(widget_2);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(120, 160, 41, 20));
        label_18->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_19 = new QLabel(widget_2);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(170, 160, 63, 20));
        label_19->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_16 = new QLabel(widget_2);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(50, 10, 121, 61));
        label_16->setScaledContents(true);
        pushButton_9 = new QPushButton(widget_2);
        pushButton_9->setObjectName("pushButton_9");
        pushButton_9->setGeometry(QRect(180, 30, 21, 29));
        pushButton_9->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        label_6->raise();
        label->raise();
        textEdit->raise();
        label_17->raise();
        label_18->raise();
        label_19->raise();
        label_16->raise();
        pushButton_9->raise();

        horizontalLayout->addWidget(widget_2);

        Dashboard->setCentralWidget(centralwidget);

        retranslateUi(Dashboard);

        stackedWidget->setCurrentIndex(2);
        stackedWidget_2->setCurrentIndex(0);
        stackedWidget_3->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Dashboard);
    } // setupUi

    void retranslateUi(QMainWindow *Dashboard)
    {
        Dashboard->setWindowTitle(QCoreApplication::translate("Dashboard", "MainWindow", nullptr));
        pushButton_3->setText(QCoreApplication::translate("Dashboard", "Home", nullptr));
        pushButton_4->setText(QCoreApplication::translate("Dashboard", "Search Car", nullptr));
        pushButton_5->setText(QCoreApplication::translate("Dashboard", "Become a Seller", nullptr));
        label_5->setText(QString());
        label_7->setText(QCoreApplication::translate("Dashboard", "AutoOracle", nullptr));
        pushButton_6->setText(QCoreApplication::translate("Dashboard", "Profile", nullptr));
        pushButton_7->setText(QCoreApplication::translate("Dashboard", "About", nullptr));
        pushButton->setText(QString());
        pushButton_2->setText(QString());
        label_2->setText(QCoreApplication::translate("Dashboard", "Home page", nullptr));
        label_8->setText(QCoreApplication::translate("Dashboard", "Dashboard", nullptr));
        label_3->setText(QCoreApplication::translate("Dashboard", "Search car with sorting", nullptr));
        label_176->setText(QCoreApplication::translate("Dashboard", "About Us", nullptr));
        pushButton_23->setText(QCoreApplication::translate("Dashboard", "Next Page", nullptr));
        label_177->setText(QString());
        label_178->setText(QCoreApplication::translate("Dashboard", "Welcome to AutoOracle, where we prioritize trust, empowerment, \n"
"and transparency to redefine your car selling experience.\n"
" Here is how we embody our 3 core values:\n"
"\n"
"\n"
"Trust:\n"
"At AutoOracle, we build trust through honesty\n"
" and integrity, ensuring confidence in our valuations and process.\n"
" Your trust is our most valued asset.\n"
"\n"
"Empowerment:\n"
"We believe in empowering you throughout the selling journey. Our platform\n"
" puts you in control, allowing you to showcase your vehicle, set terms, \n"
"and navigate the process at your pace.\n"
"\n"
"Transparency:\n"
"We're committed to transparency\342\200\224no hidden fees, no surprises.\n"
" From valuation to transaction, clear communication ensures you're\n"
"informed every step of the way. Your peace of mind is our priority.\n"
"\n"
"\n"
"Join AutoOracle today and experience a car selling experience \n"
"built on trust, empowerment, and transparency.", nullptr));
        label_179->setText(QCoreApplication::translate("Dashboard", "EMPOWERMENT", nullptr));
        label_180->setText(QCoreApplication::translate("Dashboard", "TRANSPARENCY", nullptr));
        label_181->setText(QCoreApplication::translate("Dashboard", "TRUST", nullptr));
        pushButton_24->setText(QCoreApplication::translate("Dashboard", "Previous Page", nullptr));
        label_182->setText(QString());
        label_183->setText(QString());
        label_184->setText(QCoreApplication::translate("Dashboard", "Our Journey over the years", nullptr));
        label_185->setText(QCoreApplication::translate("Dashboard", " 2006", nullptr));
        label_186->setText(QCoreApplication::translate("Dashboard", " 2023", nullptr));
        label_187->setText(QCoreApplication::translate("Dashboard", " 2015", nullptr));
        label_188->setText(QCoreApplication::translate("Dashboard", "In 2006, AutoOracle emerged, founded\n"
" on a vision to optimize and simplify the\n"
" car-buying experience. With a modest\n"
" team, the company set out to revolutionize\n"
" the automotive market.", nullptr));
        label_189->setText(QCoreApplication::translate("Dashboard", "In 2023, AutoOracle leads not just in sales\n"
" but in sustainability. Introducing\n"
" electric and hybrid vehicles, the company\n"
" emphasizes eco-friendly practices, paving\n"
" the way for a more responsible future in the\n"
" automotive industry.", nullptr));
        label_190->setText(QCoreApplication::translate("Dashboard", "By 2015, AutoOracle became a leader by\n"
" embracing the digital shift. Launching the\n"
" intuitive online platform (very same you are\n"
" reading this on!) it redefined car\n"
" purchasing, allowing customers to browse\n"
" and customize vehicles from their homes.", nullptr));
        label_9->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_10->setText(QCoreApplication::translate("Dashboard", "UserName:", nullptr));
        label_11->setText(QCoreApplication::translate("Dashboard", "UserID:", nullptr));
        label_12->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_13->setText(QCoreApplication::translate("Dashboard", "Check Password: ", nullptr));
        label_14->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_15->setText(QCoreApplication::translate("Dashboard", "Description:", nullptr));
        label_20->setText(QCoreApplication::translate("Dashboard", "Age:", nullptr));
        label_21->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_22->setText(QString());
        pushButton_8->setText(QCoreApplication::translate("Dashboard", "Change Profile Pic", nullptr));
        pushButton_10->setText(QCoreApplication::translate("Dashboard", "Change", nullptr));
        lineEdit->setPlaceholderText(QCoreApplication::translate("Dashboard", "Enter a new description", nullptr));
        comboBox->setItemText(0, QCoreApplication::translate("Dashboard", "Below 18", nullptr));
        comboBox->setItemText(1, QCoreApplication::translate("Dashboard", "18", nullptr));
        comboBox->setItemText(2, QCoreApplication::translate("Dashboard", "19", nullptr));
        comboBox->setItemText(3, QCoreApplication::translate("Dashboard", "20", nullptr));
        comboBox->setItemText(4, QCoreApplication::translate("Dashboard", "21", nullptr));
        comboBox->setItemText(5, QCoreApplication::translate("Dashboard", "22", nullptr));
        comboBox->setItemText(6, QCoreApplication::translate("Dashboard", "23", nullptr));
        comboBox->setItemText(7, QCoreApplication::translate("Dashboard", "24", nullptr));
        comboBox->setItemText(8, QCoreApplication::translate("Dashboard", "25", nullptr));
        comboBox->setItemText(9, QCoreApplication::translate("Dashboard", "26", nullptr));
        comboBox->setItemText(10, QCoreApplication::translate("Dashboard", "27", nullptr));
        comboBox->setItemText(11, QCoreApplication::translate("Dashboard", "28", nullptr));
        comboBox->setItemText(12, QCoreApplication::translate("Dashboard", "29", nullptr));
        comboBox->setItemText(13, QCoreApplication::translate("Dashboard", "30", nullptr));

        pushButton_11->setText(QCoreApplication::translate("Dashboard", "Change", nullptr));
        pushButton_12->setText(QCoreApplication::translate("Dashboard", "Change", nullptr));
        pushButton_13->setText(QCoreApplication::translate("Dashboard", "Change", nullptr));
        pushButton_14->setText(QCoreApplication::translate("Dashboard", "Change", nullptr));
        label_24->setText(QString());
        label_25->setText(QString());
        label_26->setText(QString());
        label_27->setText(QString());
        label_28->setText(QString());
        label_29->setText(QString());
        label_30->setText(QString());
        label_31->setText(QString());
        label_32->setText(QString());
        label_33->setText(QString());
        label_34->setText(QString());
        label_145->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_144->setText(QCoreApplication::translate("Dashboard", "Status:", nullptr));
        label_140->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_143->setText(QCoreApplication::translate("Dashboard", "Rs.", nullptr));
        label_147->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_146->setText(QString());
        label_23->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_149->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_154->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_152->setText(QCoreApplication::translate("Dashboard", "Rs.", nullptr));
        label_148->setText(QString());
        label_153->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_150->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_151->setText(QCoreApplication::translate("Dashboard", "Status:", nullptr));
        label_158->setText(QCoreApplication::translate("Dashboard", "Status:", nullptr));
        label_160->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_157->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_161->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_156->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_155->setText(QString());
        label_159->setText(QCoreApplication::translate("Dashboard", "Rs.", nullptr));
        label_164->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_168->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_166->setText(QCoreApplication::translate("Dashboard", "Rs.", nullptr));
        label_165->setText(QCoreApplication::translate("Dashboard", "Status:", nullptr));
        label_167->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_162->setText(QString());
        label_163->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_170->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_173->setText(QCoreApplication::translate("Dashboard", "Rs.", nullptr));
        label_174->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_172->setText(QCoreApplication::translate("Dashboard", "Status:", nullptr));
        label_171->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_169->setText(QString());
        label_175->setText(QCoreApplication::translate("Dashboard", "-", nullptr));
        label_35->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_36->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_37->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_38->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_39->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_40->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_41->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_42->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_43->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_44->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_45->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_46->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_47->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_48->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_49->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_50->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_51->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_52->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_53->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_54->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_55->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_56->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_57->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_58->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_59->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_60->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_61->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_62->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_63->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_64->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_65->setText(QString());
        label_66->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_67->setText(QString());
        label_68->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_69->setText(QString());
        label_70->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_71->setText(QString());
        label_72->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_73->setText(QString());
        label_74->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_75->setText(QString());
        label_76->setText(QString());
        label_77->setText(QString());
        label_78->setText(QString());
        label_79->setText(QString());
        label_80->setText(QString());
        label_81->setText(QString());
        label_82->setText(QString());
        label_83->setText(QString());
        label_84->setText(QString());
        label_85->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_86->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_87->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_88->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_89->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_90->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_91->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_92->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_93->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_94->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_95->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_96->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_97->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_98->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_99->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_100->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_101->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_102->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_103->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_104->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_105->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_106->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_107->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_108->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_109->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_110->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_111->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_112->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_113->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_114->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_115->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_116->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_117->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_118->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_119->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_120->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_121->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_122->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_123->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_124->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        pushButton_15->setText(QCoreApplication::translate("Dashboard", "Next", nullptr));
        pushButton_16->setText(QCoreApplication::translate("Dashboard", "Previous", nullptr));
        pushButton_17->setText(QCoreApplication::translate("Dashboard", "Next", nullptr));
        pushButton_18->setText(QCoreApplication::translate("Dashboard", "Previous", nullptr));
        label_128->setText(QCoreApplication::translate("Dashboard", "Email", nullptr));
        label_129->setText(QCoreApplication::translate("Dashboard", "Phone", nullptr));
        label_130->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_131->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        pushButton_20->setText(QCoreApplication::translate("Dashboard", "Change", nullptr));
        pushButton_21->setText(QCoreApplication::translate("Dashboard", "Change", nullptr));
        label_4->setText(QCoreApplication::translate("Dashboard", "Sell your car", nullptr));
        label_125->setText(QCoreApplication::translate("Dashboard", "Email:", nullptr));
        pushButton_19->setText(QCoreApplication::translate("Dashboard", "ENTER", nullptr));
        label_126->setText(QCoreApplication::translate("Dashboard", "Phone Number :", nullptr));
        label_127->setText(QCoreApplication::translate("Dashboard", "Description :", nullptr));
        label_132->setText(QCoreApplication::translate("Dashboard", "To Become A Seller Enter Few Details :", nullptr));
        comboBox_2->setItemText(0, QCoreApplication::translate("Dashboard", "Corolla", nullptr));
        comboBox_2->setItemText(1, QCoreApplication::translate("Dashboard", "Ford Mustang", nullptr));
        comboBox_2->setItemText(2, QCoreApplication::translate("Dashboard", "Toyota Fortuner", nullptr));
        comboBox_2->setItemText(3, QCoreApplication::translate("Dashboard", "Camaro", nullptr));
        comboBox_2->setItemText(4, QCoreApplication::translate("Dashboard", "Tata Nexon", nullptr));
        comboBox_2->setItemText(5, QCoreApplication::translate("Dashboard", "Camry", nullptr));
        comboBox_2->setItemText(6, QCoreApplication::translate("Dashboard", "Yaris", nullptr));
        comboBox_2->setItemText(7, QCoreApplication::translate("Dashboard", "Hyundai Venue", nullptr));
        comboBox_2->setItemText(8, QCoreApplication::translate("Dashboard", "Ford Escape", nullptr));
        comboBox_2->setItemText(9, QCoreApplication::translate("Dashboard", "Volkswagen Beetle", nullptr));
        comboBox_2->setItemText(10, QCoreApplication::translate("Dashboard", "Passat", nullptr));
        comboBox_2->setItemText(11, QCoreApplication::translate("Dashboard", "Toyota RAV4", nullptr));
        comboBox_2->setItemText(12, QCoreApplication::translate("Dashboard", "Civic", nullptr));
        comboBox_2->setItemText(13, QCoreApplication::translate("Dashboard", "Prius", nullptr));
        comboBox_2->setItemText(14, QCoreApplication::translate("Dashboard", "BMW 5 Series", nullptr));

        label_133->setText(QCoreApplication::translate("Dashboard", "Model:", nullptr));
        label_134->setText(QCoreApplication::translate("Dashboard", "Manufacturer:", nullptr));
        label_135->setText(QCoreApplication::translate("Dashboard", "Year of Manufacture:", nullptr));
        label_136->setText(QCoreApplication::translate("Dashboard", "Price:", nullptr));
        label_137->setText(QCoreApplication::translate("Dashboard", "Total Cylinders:", nullptr));
        label_138->setText(QCoreApplication::translate("Dashboard", "Fuel:", nullptr));
        label_139->setText(QCoreApplication::translate("Dashboard", "Paint Color:", nullptr));
        label_141->setText(QCoreApplication::translate("Dashboard", "Description:", nullptr));
        pushButton_22->setText(QCoreApplication::translate("Dashboard", "Post", nullptr));
        label_142->setText(QCoreApplication::translate("Dashboard", "Enter Your Car Details", nullptr));
        label->setText(QCoreApplication::translate("Dashboard", "M. Shariq Nadeem", nullptr));
        label_6->setText(QString());
        label_17->setText(QCoreApplication::translate("Dashboard", "Description", nullptr));
        label_18->setText(QCoreApplication::translate("Dashboard", "Age:", nullptr));
        label_19->setText(QCoreApplication::translate("Dashboard", "TextLabel", nullptr));
        label_16->setText(QString());
        pushButton_9->setText(QCoreApplication::translate("Dashboard", ">", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Dashboard: public Ui_Dashboard {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DASHBOARD_H
